name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        dotnet:
          - 5.0.x
        node-version:
          - 14.x
        ocaml-compiler:
          - 4.12.x

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Use .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - name: Install .NET Dependencies
        run: dotnet restore
           | dotnet tool restore

        run: opam install js_of_ocaml-compiler js_of_ocaml-ppx ojs

      - name: Install OCaml Dependencies
        run: opam pin add gen_js_api https://github.com/LexiFi/gen_js_api.git -y
           | opam install js_of_ocaml -y

      - name: Run FAKE
        run: dotnet fake build target All

      - name: Push js_of_ocaml standard library to jsoo-stdlib
        if: success()
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: jsoo-stdlib
          FOLDER: dist_jsoo
          TAG: jsoo-stdlib-${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build ({sha}) {msg}"

      - name: NPM Publish
        if: success()
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true
